steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - ${_IMAGE_URI}
      - .

  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - ${_IMAGE_URI}

images:
  - ${_IMAGE_URI}

substitutions:
  _IMAGE_URI: asia-northeast1-docker.pkg.dev/$PROJECT_ID/sleap-check/sleap-check-backend:latest
